[project]
name = "auto-check-in"
version = "0.1.0"
description = "自动签到脚本"
authors = [
    { name = "ultra-nexus", email = "ultra-nexus@outlook.com" }
]
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
    "lxml>=6.1.1",
    "requests>=2.34.2",
    "urllib3>=2.7.0",
]

[project.scripts]
auto-check-in = "auto_check_in.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["auto_check_in"]
